=== DissonantAU/VeadotubeTouchPortalPlugin/releasesSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "mainBranch",
    "releasesUrl"
  ],
  "properties": {
    "releasesUrl": {
      "type": "string",
      "$ref": "#/definitions/downloadUrl"
    },
    "releasesLatestUrl": {
      "type": "string",
      "$ref": "#/definitions/downloadUrl"
    },
    "mainBranch": {
      "type": "object",
      "$ref": "#/definitions/branchData"
    },
    "devBranch": {
      "type": "object",
      "$ref": "#/definitions/branchData"
    }
  },
  "definitions": {
    "branchData": {
      "type": "object",
      "required": [
        "latestRelease",
        "releases"
      ],
      "properties": {
        "latestRelease": {
          "type": "string",
          "$ref": "#/definitions/semVer"
        },
        "recommendedRelease": {
          "type": "string",
          "$ref": "#/definitions/semVer"
        },
        "releases": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "ver",
              "url"
            ],
            "properties": {
              "ver": {
                "type": "string",
                "$ref": "#/definitions/semVer"
              },
              "url": {
                "type": "string",
                "$ref": "#/definitions/downloadUrl"
              },
              "urlDlExternal": {
                "type": "string",
                "$ref": "#/definitions/downloadUrl"
              },
              "urlDlEmbedded": {
                "type": "string",
                "$ref": "#/definitions/downloadUrl"
              },
              "recommendedNextVer": {
                "type": "string",
                "$ref": "#/definitions/semVer"
              },
              "recommendedNextVerManual": {
                "type": "boolean"
              }
            }
          }
        }
      }
    },
    "semVer": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    },
    "downloadUrl": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?://"
    }
  }
}

=== DissonantAU/VeadotubeTouchPortalPlugin/releases.json
{
  "releasesUrl": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases",
  "releasesLatestUrl": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/latest",
  "mainBranch": {
    "latestRelease": "0.0.1",
    "recommendedRelease": "0.0.1",
    "releases": [
      {
        "ver": "0.1.0",
        "url": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/tag/v0.6",
        "recommendedNextVer": "0.2.0"
      }
    ]
  },
  "devBranch": {
    "latestRelease": "0.7.1-beta",
    "recommendedRelease": "0.7.1-beta",
    "releases": [
      {
        "ver": "0.7.0-beta",
        "url": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/tag/0.7.0-beta",
        "urlDlExternal":"https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/download/0.7.0-beta/VeadoTouchPlugin_0.7.0-beta.20241207+debug.tpp"
      },
      {
        "ver": "0.7.1-beta",
        "url": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/tag/0.7.1-beta",
        "urlDlExternal": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/download/0.7.1-beta/VeadoTouchPlugin_0.7.1-beta.20241210+debug.tpp",
        "urlDlBundled": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/download/0.7.1-beta/VeadoTouchPlugin_0.7.1-beta.20241210+internalJava-debug.tpp"
      },
      {
        "ver": "0.6.0-beta",
        "url": "https://github.com/DissonantAU/VeadotubeTouchPortalPlugin/releases/tag/v0.6",
        "recommendedNextVer": "0.7.1-beta",
        "recommendedNextVerManual": false
      }
    ]
  }
}
